module.exports={
    devServer:{
        proxy:{
            '/api':{
                target:'http://39.106.163.107:8080',
                changeOrigin:true,
                ws:true,
                logLevel:'debug'
            }
        }
    }
}
